-- Table: order_forms
CREATE TABLE order_forms (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  orderId uuid REFERENCES orders(id) ON DELETE CASCADE,
  firstName text NOT NULL,
  lastName text NOT NULL,
  email text NOT NULL,
  phone text,
  company text,
  street text,
  city text,
  postalCode text,
  country text,
  packId uuid REFERENCES packs(id),
  packTitle text,
  packDescription text,
  packFeatures text[],
  packDeliveryTime text,
  maintenanceId uuid REFERENCES maintenance_options(id),
  maintenanceTitle text,
  maintenanceDescription text,
  maintenanceFeatures text[],
  maintenanceBillingCycle text,
  socialOptions text[], -- liste d'ids ou noms des options sociales sélectionnées
  additionalInfo text,
  budget text,
  objectif text,
  delai text,
  referenceUrl text,
  description text,
  color text,
  logoUrl text,
  imageUrl text,
  domain text,
  cms text,
  hebergement text,
  paiement text,
  livraison text,
  produit text,
  service text,
  autre text,
  besoin text,
  fonctionnalite text,
  rgpdAccepted boolean,
  status text DEFAULT 'en cours de validation' CHECK (status IN ('en cours de validation', 'site en construction', 'site livré')),
  createdAt timestamptz DEFAULT now()
);

-- Cette table reprend tous les champs typiques d'un flow e-commerce multi-étapes.
-- Ajoutez/ajustez les colonnes selon les champs exacts de votre formulaire.
